# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo CI starts
  displayName: 'Start of CI'

- script: |
    echo Install UT framework Mocha.
    npm install --global mocha
    echo run unit test
    mocha
  displayName: 'run unit test'

- script: echo CI completes
  displayName: 'End of CI'
