# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo CI starts
  displayName: 'Start of CI'

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  inputs:
  command: 'install'

- script: |
    echo run unit test using mocha.
    npx mocha
  displayName: 'run unit test'

- script: echo CI completes
  displayName: 'End of CI'
